; The sequence of triangle numbers is generated by adding the 
; natural numbers. So the 7th triangle number would be
; 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

; Let us list the factors of the first seven triangle numbers:

;  1: 1
;  3: 1,3
;  6: 1,2,3,6
; 10: 1,2,5,10
; 15: 1,3,5,15
; 21: 1,3,7,21
; 28: 1,2,4,7,14,28

; We can see that 28 is the first triangle number to have over 
; five divisors. What is the value of the first triangle 
; number to have over five hundred divisors?


;more efficient algo for calculating factors
(defn factors [n]
  (count (into (sorted-set)
    (mapcat (fn [x] [x (/ n x)])
      (filter #(zero? (rem n %)) (range 1 (inc (Math/sqrt n)))) ))))

(def triangle_numbers 
  (lazy-cat [0]
    (map + triangle_numbers (iterate inc 1))))

(defn first_triangle [divisors]
  (first (filter #(> (factors %) divisors) triangle_numbers)))

; (first_triangle 500) => 76576500